import Head from "./head/layout";
import "./globals.css";
import Footer from "./footer/layout";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) { 
  return (
    <html lang="en">
      <body className="box-border overflow-x-hidden">
        <Head/>
        {children}
        <Footer/>
        <p className="py-6 font-medium text-center">© 2024 All Rights Reserved By Free Html Templates</p>
      </body>
    </html>
  );
}
